# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: pdf_generator.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC, 6, 31, 1, "", "pdf_generator.proto"
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\x13pdf_generator.proto\x12\x0b\x63\x65rtificate"5\n\nPDFRequest\x12\x14\n\x0chtml_content\x18\x01 \x01(\t\x12\x11\n\tfile_name\x18\x02 \x01(\t"A\n\x0bPDFResponse\x12\x10\n\x08pdf_data\x18\x01 \x01(\x0c\x12\x0f\n\x07message\x18\x02 \x01(\t\x12\x0f\n\x07success\x18\x03 \x01(\x08\x32P\n\x0cPDFGenerator\x12@\n\x0bGeneratePDF\x12\x17.certificate.PDFRequest\x1a\x18.certificate.PDFResponseB>Z<github.com/SiddhantTotade/go_html_to_pdf/proto;pdf_generatorb\x06proto3'
)

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, "pdf_generator_pb2", _globals)
if not _descriptor._USE_C_DESCRIPTORS:
    _globals["DESCRIPTOR"]._loaded_options = None
    _globals["DESCRIPTOR"]._serialized_options = (
        b"Z<github.com/SiddhantTotade/go_html_to_pdf/proto;pdf_generator"
    )
    _globals["_PDFREQUEST"]._serialized_start = 36
    _globals["_PDFREQUEST"]._serialized_end = 89
    _globals["_PDFRESPONSE"]._serialized_start = 91
    _globals["_PDFRESPONSE"]._serialized_end = 156
    _globals["_PDFGENERATOR"]._serialized_start = 158
    _globals["_PDFGENERATOR"]._serialized_end = 238
# @@protoc_insertion_point(module_scope)
