# Generated by Django 4.1.10 on 2025-09-06 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cergen_auth', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
