# Generated by Django 4.1.3 on 2023-01-14 04:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('event_name', models.CharField(blank=True, max_length=20, null=True)),
                ('subject', models.CharField(blank=True, max_length=20, null=True)),
                ('event_department', models.CharField(blank=True, max_length=20, null=True)),
                ('from_date', models.DateField()),
                ('to_date', models.DateField()),
                ('event_year', models.IntegerField(blank=True, null=True)),
                ('slug', models.SlugField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(blank=True, max_length=50, null=True)),
                ('student_id', models.CharField(blank=True, max_length=50, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('certificate_status', models.CharField(blank=True, max_length=10, null=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cert_gen_sen_app_backend.event')),
            ],
        ),
        migrations.CreateModel(
            name='EventFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('xlsx_file', models.FileField(blank=True, null=True, upload_to='certificates/csv_files/')),
                ('event_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cert_gen_sen_app_backend.event')),
            ],
        ),
    ]
