# Generated by Django 4.1.3 on 2023-01-14 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cert_gen_sen_app_backend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='subject',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
