# Generated by Django 4.1.3 on 2023-03-04 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cert_gen_sen_app_backend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='certificate_id',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
