# Generated by Django 4.1.3 on 2023-04-09 20:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cert_gen_sen_app_backend', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
        migrations.RenameField(
            model_name='participant',
            old_name='student_id',
            new_name='participant_id',
        ),
        migrations.RenameField(
            model_name='participant',
            old_name='student_name',
            new_name='participant_name',
        ),
    ]
