# Generated by Django 4.1.3 on 2023-03-06 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cert_gen_sen_app_backend', '0002_participant_certificate_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='certificate_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
