# Generated by Django 4.1.3 on 2023-04-18 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cert_gen_sen_app_backend', '0003_alter_contributedcompletioncertificates_template_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contributedcompletioncertificates',
            name='template_img',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
