# Generated by Django 4.1.3 on 2023-03-07 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cert_gen_sen_app_backend', '0003_alter_participant_certificate_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='certificate_sent_status',
            field=models.BooleanField(default=False),
        ),
    ]
