# Generated by Django 4.1.3 on 2023-03-13 16:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cert_gen_sen_app_backend', '0004_participant_certificate_sent_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='MeritCertificateTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template', models.FileField(upload_to='./cert_gen_sen_app_backend/certificate_data/merit_certificate_templates')),
                ('template_img', models.ImageField(upload_to='./cert_gen_sen_app_backend/certificate_data/merit_certificate_template_images')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CompletionCertificateTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template', models.FileField(upload_to='./cert_gen_sen_app_backend/certificate_data/completion_certificate_templates')),
                ('template_img', models.ImageField(upload_to='./cert_gen_sen_app_backend/certificate_data/completion_certificate_template_images')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
