# Generated by Django 4.1.3 on 2023-04-19 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cert_gen_sen_app_backend', '0004_alter_contributedcompletioncertificates_template_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='completioncertificatetemplate',
            name='template_img',
            field=models.ImageField(blank=True, null=True, upload_to='completion-certificate-template/'),
        ),
        migrations.AlterField(
            model_name='contributedmeritcertificates',
            name='template_img',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='meritcertificatetemplate',
            name='template_img',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
