# Generated by Django 4.1.3 on 2022-11-25 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cert_gen_sen_app_backend', '0004_participant_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='from_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='event',
            name='to_date',
            field=models.DateField(),
        ),
    ]
