# Generated by Django 4.1.3 on 2023-03-15 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cert_gen_sen_app_backend', '0005_meritcertificatetemplate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='completioncertificatetemplate',
            name='template_img',
            field=models.ImageField(null=True, upload_to='./cert_gen_sen_app_backend/certificate_data/completion_certificate_template_images'),
        ),
    ]
