# Generated by Django 4.1.3 on 2022-11-25 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cert_gen_sen_app_backend', '0005_alter_event_from_date_alter_event_to_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='csv_file',
            new_name='xlsx_file',
        ),
    ]
