# Generated by Django 4.1.3 on 2023-04-23 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cert_gen_sen_app_backend', '0006_alter_completioncertificatetemplate_template_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participant',
            name='student_image',
        ),
        migrations.AddField(
            model_name='participant',
            name='participant_image',
            field=models.ImageField(blank=True, null=True, upload_to='participant-images'),
        ),
    ]
