# Generated by Django 4.1.3 on 2022-11-27 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cert_gen_sen_app_backend', '0006_rename_csv_file_event_xlsx_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='xlsx_file',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
