# Generated by Django 4.1.3 on 2023-03-16 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cert_gen_sen_app_backend', '0007_alter_completioncertificatetemplate_template_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='completioncertificatetemplate',
            name='template',
            field=models.FileField(upload_to='completion-certificate-templates/'),
        ),
        migrations.AlterField(
            model_name='completioncertificatetemplate',
            name='template_img',
            field=models.ImageField(blank=True, null=True, upload_to='completion-certificate-template-images/'),
        ),
        migrations.AlterField(
            model_name='meritcertificatetemplate',
            name='template',
            field=models.FileField(upload_to='merit-certificate-templates/'),
        ),
        migrations.AlterField(
            model_name='meritcertificatetemplate',
            name='template_img',
            field=models.ImageField(blank=True, null=True, upload_to='merit-certificate-template-images/'),
        ),
    ]
