# Generated by Django 4.1.3 on 2023-04-23 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cert_gen_sen_app_backend', '0007_remove_participant_student_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='participant_image',
            field=models.ImageField(blank=True, null=True, upload_to='participant-image'),
        ),
    ]
