# Generated by Django 4.1.3 on 2022-11-27 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cert_gen_sen_app_backend', '0007_alter_event_xlsx_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='xlsx_file',
            field=models.FileField(blank=True, null=True, upload_to='certificates/csv_files/'),
        ),
    ]
