# Generated by Django 4.1.3 on 2022-12-01 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cert_gen_sen_app_backend', '0008_alter_event_xlsx_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='certificate_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='participant',
            name='student_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
