# Generated by Django 4.1.3 on 2023-04-29 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cert_gen_sen_app_backend', '0008_alter_participant_participant_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='senders_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='senders_password',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='senders_phone',
            field=models.CharField(blank=True, max_length=13, null=True),
        ),
    ]
