# Generated by Django 4.1.3 on 2022-12-11 12:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cert_gen_sen_app_backend', '0009_participant_certificate_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='xlsx_file',
        ),
        migrations.CreateModel(
            name='EventFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('xlsx_file', models.FileField(blank=True, null=True, upload_to='certificates/csv_files/')),
                ('event_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cert_gen_sen_app_backend.event')),
            ],
        ),
    ]
