# Generated by Django 4.1.3 on 2023-05-01 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cert_gen_sen_app_backend', '0010_remove_user_senders_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='certificate_file_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='certificates_file',
            field=models.FileField(default='', upload_to='pdf-certificates-files'),
        ),
    ]
