# Generated by Django 4.1.3 on 2022-12-13 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cert_gen_sen_app_backend', '0010_remove_event_xlsx_file_eventfile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='certificate_status',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
