# Generated by Django 4.1.3 on 2023-03-19 15:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cert_gen_sen_app_backend', '0010_alter_completioncertificatetemplate_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContributedCertificates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template', models.FileField(upload_to='contributed-certificate-templates/')),
                ('template_img', models.ImageField(blank=True, null=True, upload_to='contributed-certificate-template-images/')),
            ],
        ),
        migrations.AlterField(
            model_name='completioncertificatetemplate',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='meritcertificatetemplate',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
