# Generated by Django 4.1.3 on 2023-01-10 15:02

import cert_gen_sen_app_backend.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cert_gen_sen_app_backend', '0012_alter_event_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event_department',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='event_year',
            field=models.PositiveIntegerField(default=2023, validators=[django.core.validators.MinValueValidator(1984), cert_gen_sen_app_backend.models.max_value_current_year]),
        ),
        migrations.AddField(
            model_name='participant',
            name='student_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
