# Generated by Django 4.1.3 on 2023-03-20 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cert_gen_sen_app_backend', '0012_contributedcompletioncertificates_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='student_image',
            field=models.ImageField(blank=True, upload_to='students-images/'),
        ),
    ]
