# Generated by Django 4.1.3 on 2023-03-21 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cert_gen_sen_app_backend', '0013_participant_student_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='student_image',
            field=models.TextField(blank=True),
        ),
    ]
