# Generated by Django 4.1.3 on 2023-03-30 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cert_gen_sen_app_backend', '0015_participantalbum'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='phone',
            field=models.CharField(blank=True, max_length=13),
        ),
    ]
